import type { JsonObject } from "./domain/errors.js";

/** Stable discovery identifier for the standalone local execution contract. */
export const MACHINE_CONTRACT_ID = "nawabari.standalone-execution.v1" as const;
export const MACHINE_CONTRACT_SCHEMA_VERSION = 1 as const;

const MACHINE_CONTRACT_CAPABILITIES = Object.freeze([
  {
    id: "session-lifecycle",
    commands: ["session create", "session id", "session show", "session list", "status", "session close"],
    result_schema: "session.v1",
    identities: ["session_id", "repository", "worktree", "branch", "state"],
    failure_codes: [
      "NOT_GIT_REPOSITORY",
      "PROTECTED_WORKTREE",
      "PROTECTED_BRANCH",
      "WORKTREE_ALREADY_EXISTS",
      "BRANCH_ALREADY_EXISTS",
      "INVALID_SESSION_ID",
      "INVALID_BASE_REF",
      "INVALID_BRANCH",
      "INVALID_WORKTREE",
      "WORKTREE_OWNED_BY_OTHER_SESSION",
      "BRANCH_OWNED_BY_OTHER_SESSION",
      "REPOSITORY_MISMATCH",
      "WORKTREE_MISMATCH",
      "BRANCH_MISMATCH",
      "STALE_REGISTRY",
      "GIT_STATE_AMBIGUOUS",
      "PHYSICAL_OBSERVATION_UNAVAILABLE",
      "SESSION_NOT_FOUND",
      "NO_CURRENT_SESSION",
      "DIRTY_WORKTREE",
      "RECOVERABLE_COMMITS",
      "RECOVERABLE_STASHES",
      "MISSING_WORKTREE",
      "INVALID_REGISTRY",
      "OPERATION_REJECTED",
      "REGISTRY_CORRUPT",
      "REGISTRY_UNREADABLE",
      "REGISTRY_DURABILITY_UNCERTAIN",
      "LOCK_CONTENTION",
      "GIT_COMMAND_FAILED",
      "GIT_SPAWN_FAILED",
      "GIT_TIMEOUT",
      "GIT_OUTPUT_LIMIT",
    ],
  },
  {
    id: "resource-claims",
    commands: ["session claim", "session update", "session claims", "session release"],
    result_schema: "claim.v1",
    identities: ["claim_id", "session_id", "repository", "worktree", "resource", "mode"],
    failure_codes: [
      "INVALID_CLAIM",
      "INVALID_SESSION_ID",
      "INVALID_RESOURCE",
      "INVALID_REGISTRY",
      "NOT_GIT_REPOSITORY",
      "SESSION_NOT_FOUND",
      "NO_CURRENT_SESSION",
      "REPOSITORY_MISMATCH",
      "INVALID_CLAIM_RESOURCE",
      "CLAIM_PATH_TRAVERSAL",
      "CLAIM_SYMLINK_ESCAPE",
      "CLAIM_AMBIGUOUS_PATH",
      "UNSUPPORTED_CLAIM_GLOB",
      "CLAIM_REPOSITORY_MISMATCH",
      "CLAIM_SESSION_MISMATCH",
      "DUPLICATE_CLAIM",
      "CONTRADICTORY_CLAIM",
      "RESOURCE_CLAIM_CONFLICT",
      "CLAIM_NOT_FOUND",
      "SESSION_NOT_ACTIVE",
      "WORKTREE_OWNED_BY_OTHER_SESSION",
      "BRANCH_OWNED_BY_OTHER_SESSION",
      "GIT_COMMAND_FAILED",
      "GIT_SPAWN_FAILED",
      "GIT_TIMEOUT",
      "GIT_OUTPUT_LIMIT",
      "REGISTRY_CORRUPT",
      "REGISTRY_UNREADABLE",
      "REGISTRY_DURABILITY_UNCERTAIN",
      "LOCK_CONTENTION",
    ],
  },
  {
    id: "authorization-and-evidence",
    commands: ["guard", "authorize", "checkpoint"],
    result_schema: "decision.v1 / evidence.v1",
    identities: ["operation", "allowed", "code", "claim_ids", "head", "in_claim", "out_of_claim"],
    failure_codes: [
      "INVALID_OPERATION",
      "INVALID_SESSION_ID",
      "INVALID_RESOURCE",
      "MISSING_RESOURCE_CLAIM",
      "INSUFFICIENT_CLAIM_MODE",
      "RESOURCE_CLAIM_CONFLICT",
      "SESSION_NOT_FOUND",
      "SESSION_NOT_ACTIVE",
      "NOT_GIT_REPOSITORY",
      "MISSING_WORKTREE",
      "REPOSITORY_MISMATCH",
      "WORKTREE_MISMATCH",
      "BRANCH_MISMATCH",
      "DETACHED_HEAD",
      "STALE_REGISTRY",
      "GIT_STATE_AMBIGUOUS",
      "PHYSICAL_OBSERVATION_UNAVAILABLE",
      "GIT_COMMAND_FAILED",
      "WORKTREE_OWNED_BY_OTHER_SESSION",
      "BRANCH_OWNED_BY_OTHER_SESSION",
      "OWNERSHIP_MISMATCH",
      "REGISTRY_CORRUPT",
      "REGISTRY_UNREADABLE",
      "LOCK_CONTENTION",
    ],
  },
  {
    id: "repository-evidence",
    commands: ["evidence snapshot", "diff"],
    result_schema: "repository-evidence.v1 / diff.v1",
    identities: [
      "session_id",
      "repository",
      "worktree",
      "branch_id",
      "branch",
      "session_state",
      "base_revision",
      "head",
      "evidence_hash",
    ],
    failure_codes: [
      "INVALID_SESSION_ID",
      "SESSION_NOT_FOUND",
      "STALE_REGISTRY",
      "OWNERSHIP_MISMATCH",
      "NOT_GIT_REPOSITORY",
      "MISSING_WORKTREE",
      "REPOSITORY_MISMATCH",
      "WORKTREE_MISMATCH",
      "BRANCH_MISMATCH",
      "DETACHED_HEAD",
      "GIT_STATE_AMBIGUOUS",
      "PHYSICAL_OBSERVATION_UNAVAILABLE",
      "GIT_COMMAND_FAILED",
      "GIT_SPAWN_FAILED",
      "GIT_TIMEOUT",
      "GIT_OUTPUT_LIMIT",
      "REGISTRY_CORRUPT",
      "REGISTRY_UNREADABLE",
      "LOCK_CONTENTION",
    ],
  },
  {
    id: "governed-git-mutation",
    commands: ["commit", "push"],
    result_schema: "commit.v1 / push.v1",
    identities: [
      "commit_sha",
      "source_sha",
      "remote",
      "branch",
      "target",
      "target_ref",
      "observed_remote_sha",
      "relation",
    ],
    failure_codes: [
      "INVALID_COMMIT_MESSAGE",
      "INVALID_SESSION_ID",
      "INVALID_OPERATION",
      "INVALID_RESOURCE",
      "MISSING_RESOURCE_CLAIM",
      "INSUFFICIENT_CLAIM_MODE",
      "RESOURCE_CLAIM_CONFLICT",
      "SESSION_NOT_FOUND",
      "SESSION_NOT_ACTIVE",
      "COMMIT_EMPTY_DIFF",
      "UNEXPECTED_CHANGED_PATHS",
      "COMMIT_STAGING_FAILED",
      "COMMIT_FAILED",
      "COMMIT_RESULT_UNAVAILABLE",
      "COMMIT_RESULT_DIVERGED",
      "GIT_STATE_AMBIGUOUS",
      "INVALID_REMOTE",
      "INVALID_REMOTE_BRANCH",
      "PUSH_TARGET_MISMATCH",
      "PUSH_REMOTE_INSPECTION_FAILED",
      "PUSH_NO_UPSTREAM",
      "PUSH_BEHIND",
      "PUSH_DIVERGED",
      "PUSH_DIRTY_WORKTREE",
      "PUSH_FAILED",
      "GIT_COMMAND_FAILED",
      "GIT_SPAWN_FAILED",
      "GIT_TIMEOUT",
      "GIT_OUTPUT_LIMIT",
      "REGISTRY_CORRUPT",
      "REGISTRY_UNREADABLE",
    ],
  },
  {
    id: "reconciliation-and-cleanup",
    commands: ["doctor", "gc"],
    result_schema: "reconciliation.v1 / cleanup.v1",
    identities: ["clean", "issues", "candidates", "cleaned", "blocked", "recovery_hints"],
    failure_codes: [
      "RECONCILIATION_DRIFT",
      "DOCTOR_FAILED",
      "NOT_GIT_REPOSITORY",
      "GIT_COMMAND_FAILED",
      "GIT_SPAWN_FAILED",
      "GIT_TIMEOUT",
      "GIT_OUTPUT_LIMIT",
      "PROTECTED_WORKTREE",
      "PROTECTED_BRANCH",
      "WORKTREE_ALREADY_EXISTS",
      "BRANCH_ALREADY_EXISTS",
      "WORKTREE_OWNED_BY_OTHER_SESSION",
      "BRANCH_OWNED_BY_OTHER_SESSION",
      "MISSING_WORKTREE",
      "OWNERSHIP_MISMATCH",
      "DIRTY_WORKTREE",
      "RECOVERABLE_COMMITS",
      "RECOVERABLE_STASHES",
      "NESTED_REPOSITORY",
      "STALE_SESSION",
      "REGISTRY_CORRUPT",
      "LOCK_CONTENTION",
      "REGISTRY_UNREADABLE",
      "REGISTRY_DURABILITY_UNCERTAIN",
    ],
  },
] as const);

/**
 * Return a JSON-safe description of the installed machine contract.
 * Discovery intentionally has no repository or network precondition.
 */
export function machineContract(packageVersion: string): JsonObject {
  return {
    schema_version: MACHINE_CONTRACT_SCHEMA_VERSION,
    contract_id: MACHINE_CONTRACT_ID,
    capability_id: MACHINE_CONTRACT_ID,
    package: "nawabari",
    package_version: packageVersion,
    capabilities: MACHINE_CONTRACT_CAPABILITIES.map((capability) => ({
      id: capability.id,
      commands: [...capability.commands],
      result_schema: capability.result_schema,
      identities: [...capability.identities],
      failure_codes: [...capability.failure_codes],
    })),
    json: {
      schema_version: 1,
      success: {
        required: ["ok", "command"],
        ok: true,
        exit_code: 0,
      },
      failure: {
        required: ["ok", "command", "code", "message"],
        ok: false,
        exit_codes: {
          usage: 2,
          rejected: 3,
          unavailable: 4,
          doctor: 5,
          internal: 70,
        },
        stderr: "empty",
      },
      one_document: true,
      human_output_is_not_contract: true,
    },
    bounded_local_execution: {
      git_timeout_ms: 10_000,
      git_max_output_bytes: 65_536,
      checkpoint_max_paths: 4_096,
      evidence_max_paths: 4_096,
      diff_max_paths: 64,
      diff_max_bytes: 65_536,
      diff_max_hunks: 128,
    },
    dependencies: {
      local_git: true,
      network: false,
      github: false,
      gh: false,
      mottainai: false,
      llm: false,
      agent_runtime: false,
    },
  };
}
